# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               B. Shine Cho, Ph.D.
tagline:             'Public Administration Scholar exploring local government affairs'
description:         'Public administration<br />Local govenrment<br />Budgeting & financial mgmt<br />Public participation'
url:                 https://shinecho724.github.io
giturl:				       https://shinecho724.github.io
baseurl:             https://shinecho724.github.io/
paginate:            5

# About/contact
author:
  name:             B. Shine Cho
  email:            shine.cho724@gmail.com
  linkedin:         bshinecho
  google_scholar:   https://scholar.google.com/citations?user=ctmX4igAAAAJ&hl=en

# Custom vars
version:             1.0.1
